### ISSUE TITLE
Can't run `predict_rosette_leaf_count` twice

### ISSUE THREAD

**Issue by stardust66** [p2irc/deepplantphenomics#10]
Running `deepplantphenomics.tools.predict_rosette_leaf_count` twice gives the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/s180893/.local/share/virtualenvs/openag_new_cv-G6jS5ejj/lib/python3.6/site-packages/deepplantphenomics/tools.py", line 17, in predict_rosette_leaf_count
    net = networks.rosetteLeafRegressor(batch_size=batch_size)
  File "/Users/s180893/.local/share/virtualenvs/openag_new_cv-G6jS5ejj/lib/python3.6/site-packages/deepplantphenomics/networks.py", line 108, in __init__
    self.model.add_input_layer()
  File "/Users/s180893/.local/share/virtualenvs/openag_new_cv-G6jS5ejj/lib/python3.6/site-packages/deepplantphenomics/deepplantpheno.py", line 1481, in add_input_layer
    " The input layer need to be the first layer added to the model.")
RuntimeError: Trying to add an input layer to a model that already contains other layers.  The input layer need to be the first layer added to the model.
```

**Comment by nhiggs** [comment]
hi @stardust66 could you post your script or perhaps a small reproducible example of it? Just want to nail down precisely what you mean by running it twice.

**Comment by stardust66** [comment]
```python
import deepplantphenomics as dpp
dpp.tools.predict_rosette_leaf_count([image_path])
# Returns `array[17.]`

dpp.tools.predict_rosette_leaf_count([image_path])
# Raises aforementioned error.
```

**Comment by stardust66** [comment]
I think I figured out why. `DPPModel.__layers` is a class attribute instead of an instance attribute. So its value stays the same for all instances. I had `__init__` print out `self.__layers` and the second time it was called it was full of layers. That's why the error is thrown when calling the function the second time.
